name: build

on:
  push:
    branches:
      - Rebuild


jobs:
  build:
    name: build Python Wheel
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v7

      - name: Install UV
        uses: astral-sh/setup-uv@v3
        with:
          version: latest

      - name: Build
        run: |
          uv build

      - name: Upload Dist
        uses: actions/upload-artifact@v7
        with:
          name: endstone-NekoQD
          path: dist/*.whl